### ISSUE TITLE
Refactor Altium BOM generation to use list_components

### ISSUE THREAD

**Issue by shrik450** [AllSpiceIO/py-allspice#118]
Like OrCAD, we should have a `list_components` intermediate step for generating a list of components for Altium as well.

**Comment by shrik450** [comment]
Note that this could also lead to another improvement in simplifying BOM generation, as the column extraction and grouping logic are the same for all project types.

**Comment by kdumontnu** [comment]
:+1: I think this makes a lot of sense - I made [some notes previously](https://github.com/AllSpiceIO/py-allspice/pull/84#pullrequestreview-2033936819) about what the function hierarchy might look like & it might be worth reviewing.
