### ISSUE TITLE
Handle duplicate pins in netlist generation

### ISSUE THREAD

**Issue by shrik450** [AllSpiceIO/py-allspice#130]
Following up from #128 and #129, we need to re-evaluate the netlist generation code to be sure that this fix doesn't break something else and the logic is still correct.

**Comment by shrik450** [comment]
@kdumontnu Do you know if the two warnings here:

https://github.com/AllSpiceIO/py-allspice/blob/069de7c1f64445ddd3d5396444771d39e0812bc0/allspice/utils/netlist_generation.py#L79-L83

and

https://github.com/AllSpiceIO/py-allspice/blob/069de7c1f64445ddd3d5396444771d39e0812bc0/allspice/utils/netlist_generation.py#L87-L91

are "useful"? As in, is it important that we warn for these? Due the same crysknife change that broke the netlist generation, these are triggering very often, and in general the code here can be simpler without them.

**Comment by McRaeAlex** [comment]
I believe this is closed by https://github.com/AllSpiceIO/crysknife/pull/1089 but we will confirm after the next crysknife release and validate it in production 👍

**Comment by shrik450** [comment]
Tested this with 0.3.17 on local and I think we're good to close this.
