### ISSUE TITLE
Add setup of issue sync between AllSpice and GitLab server

### ISSUE THREAD

**Issue by danielallspice** [AllSpiceIO/py-allspice#15]
Customers have been asking for a way to sync issues between an AllSpice server and a GitLab server.

It would be nice to have a convenience function to sync all issues from an AllSpice sever to a GitLab server.

**Comment by shrik450** [comment]
I was thinking about this and my conclusion is that this would be better handled as an example script, like we do for BOM. The biggest reason is that we'd end up depending on a GitLab client, which isn't necessary for people who don't use GitLab and AllSpice. Another reason is that syncing quickly runs into hairy problems: we'd have to track issues that already exist on both platforms, and you might have to translate some gitea things to gitlab things on the way, which users might need control over.

**Comment by kdumontnu** [comment]
I actually think it should be another library altogether that uses the py-allspice library as the AllSpice binding, and probably a similar python interface for gitlab bindings. 

It should start as a demo script though, and if demand increases we’ll see if we can spin it out into a library.

**Comment by danielallspice** [comment]
I like the idea of sync projects starting out as API demos and then moving onto libs when they get mature.
