### ISSUE TITLE
Should change this repo to not be a fork

### ISSUE THREAD

**Issue by jtran** [AllSpiceIO/py-allspice#38]
This repo is a fork of the py-gitea repo. Forks in GitHub are not independent and can interact in unexpected ways. We should make this repo not be a fork to avoid pitfalls.

A few things that we know about, but there are probably more:

- When making a PR, the default base is the upstream
- Default notifications are not the same as for the `AllSpiceIO` organization
- Repo privacy (i.e. public/private) is tied to the upstream

**Comment by shrik450** [comment]
This can be done without deleting the repo via GitHub suppot: https://support.github.com/request?q=unfork

**Comment by jtran** [comment]
Any reason why we shouldn't do this now?

**Comment by jtran** [comment]
Done.
