### ISSUE TITLE
Update team members pagination to be 1-indexed for 1.20

### ISSUE THREAD

**Issue by shrik450** [AllSpiceIO/py-allspice#43]
Currently, AllSpice Hub is at 1.19, where the team members endpoint is paginated with a 0-based index. This was fixed in 1.20 (go-gitea/gitea#24754) and the endpoing is 1-based as documented. Right now, py-allspice uses the 0-index, and when AllSpice Hub switches to 1.20 this will lead to duplicates in the list of team members. We'll have to change `Team.get_members` when we release 1.20.

**Comment by kdumontnu** [comment]
Thanks for finding this! Can you add a cron job to schedule the CI tests nightly? I think it'll help us preemptively catch issues like this (where we might update the application to 1.20, but forget to update py-allspice).

**Comment by jtran** [comment]
Resolved by #48.
