### ISSUE TITLE
Extend generate_bom.py example to consider variants

### ISSUE THREAD

**Issue by kdumontnu** [AllSpiceIO/py-allspice#65]
Should either be able to specify the variant we want to generate the BOM for AND/OR generate a BOM for each variant.

Also might want to consider adding another column for different variant fits.

**Comment by shrik450** [comment]
@kdumontnu Could you point to an example repo on AS Hub?

**Comment by jtran** [comment]
Just a reminder that this issue/repo is public. I don't know of a public repo that has variants. I can send you something privately.
