### ISSUE TITLE
Builds fail with setuptools > 66

### ISSUE THREAD

**Issue by shrik450** [AllSpiceIO/py-allspice#71]
We use a template in our build system to fill the version based on the tag:

https://github.com/AllSpiceIO/py-allspice/blob/main/setup.py#L8

Since we don't render the template when installing (e.g. with `pip install --editable .`), setuptools throws an exception because of https://github.com/pypa/setuptools/issues/2497. This means that e.g. during the dev workflow we have to change the version to a valid PEP440 version and change it back to the template when we're pushing a new release.

**Comment by jtran** [comment]
The template in `setup.py` was removed in #73. Can this be closed?

**Comment by shrik450** [comment]
Yep
