### ISSUE TITLE
Top-level __init__.py should not exist

### ISSUE THREAD

**Issue by jtran** [AllSpiceIO/py-allspice#97]
Using mypy 1.10.0, python 3.10.

```
$ mypy allspice/
py-allspice is not a valid Python package name
```

If you rename the directory to `py_allspice` (i.e. replace hyphen with underscore):

```
$ mypy allspice/
allspice/utils/core.py: error: Source file found twice under different module names: "py_allspice.allspice.utils.core" and "allspice.utils.core"
allspice/utils/core.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
allspice/utils/core.py: note: Common resolutions include: a) adding `__init__.py` somewhere, b) using `--explicit-package-bases` or adjusting MYPYPATH
```

The solution is deleting the top-level `__init__.py` file. If you do that, mypy runs and produces errors.

Python modules are overly complicated, but this matches my understanding of how they work. At the top-level of the repo, all these files are part of the package, but it's not a module. When you pip install a package, the package's top-level directory is added to Python's search path. However, you cannot use files from it because they aren't a module. To create a module, you create a directory `allspice` with an `__init__.py` file inside it. Then when other code does `from allspice import Foo`, the `allspice` is that directory, _not_ the top-level package directory.

On the other hand, putting `__init__.py` in the top-level directory, mypy keeps looking at parent directories, and seeing `__init__.py`, it incorrectly infers that it must be a module, when it's not.

**Comment by kdumontnu** [comment]
:+1: I've had to use `export PYTHONPATH="${PYTHONPATH}:$(pwd)"` from the top level directory to be able to run scripts from the module.
