### ISSUE TITLE
BOM script shouldn't use JSON for configuration

### ISSUE THREAD

**Issue by jtran** [AllSpiceIO/py-allspice#99]

**Comment by kdumontnu** [comment]
sorry, what does this mean? Like it shouldn't use json as arguments? Or that it shouldn't use the IR JSON?

**Comment by jtran** [comment]
Sorry, the issue was created prematurely, before I had a chance to write down a detailed explanation and proposal.

**Comment by shrik450** [comment]
Wholeheartedly agree that we probably shouldn't use JSON for this. It is easy to mess up when writing by hand. A few thoughts I had about this recently:

- If we decide to drop 3.10 support a little early, we can use `tomllib` to make the configuration in TOML which is a lot more human readable and editable without having to pull in a library. 
- We can always take on a new dependency to support TOML/YAML.
- If we don't want a new dependency and yet want to change the config language, we can use `configparse` and make the config an ini file, which IMO is more human readable than JSON and supports comments.

**Comment by shrik450** [comment]
In today's discussion we decided to switch to primarily using YAML here while also supporting TOML.

**Comment by shrik450** [comment]
Closing this as we've removed the BOM script from this repo, and the YAML config was implemented in https://github.com/AllSpiceIO/generate-bom/pull/8.
